"""Local proxy chainer.

Spawns N local HTTP CONNECT proxies on 127.0.0.1, each forwarding to one
upstream Decodo endpoint (with authentication added in the upstream CONNECT
request). Chrome connects to the local port without auth — much simpler than
chaining proxy auth through DrissionPage which doesn't fully support it.

Usage:
    python tools/proxy_chain.py
        Reads upstream proxies from state/proxies.txt.
        Spawns one local listener per upstream, starting at port 18001.

After this runs, state/proxies.txt is automatically replaced (in-memory by
the crawler via env var override) with local 127.0.0.1 endpoints.
"""
from __future__ import annotations

import asyncio
import base64
import sys
from pathlib import Path
from urllib.parse import unquote, urlparse

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from crawler import config  # noqa: E402


LOCAL_BASE_PORT = 18001


async def handle_client(client_reader: asyncio.StreamReader,
                        client_writer: asyncio.StreamWriter,
                        upstream_host: str, upstream_port: int,
                        auth_b64: str):
    """Handle one CONNECT request: relay it to the upstream with Basic auth,
    then bidirectionally pipe data."""
    up_writer = None
    try:
        # Read CONNECT request line
        first_line = await asyncio.wait_for(
            client_reader.readuntil(b'\r\n'), timeout=10
        )
        if not first_line.startswith(b'CONNECT '):
            client_writer.write(b'HTTP/1.1 400 Bad Request\r\n\r\n')
            await client_writer.drain()
            return
        target = first_line.split(b' ')[1].decode()
        # Drain remaining headers
        while True:
            line = await asyncio.wait_for(
                client_reader.readuntil(b'\r\n'), timeout=10
            )
            if line == b'\r\n':
                break

        # Connect to upstream proxy
        up_reader, up_writer = await asyncio.wait_for(
            asyncio.open_connection(upstream_host, upstream_port), timeout=20
        )

        # Send CONNECT with auth
        connect_req = (
            f"CONNECT {target} HTTP/1.1\r\n"
            f"Host: {target}\r\n"
            f"Proxy-Authorization: Basic {auth_b64}\r\n"
            f"Proxy-Connection: keep-alive\r\n"
            f"\r\n"
        ).encode()
        up_writer.write(connect_req)
        await up_writer.drain()

        # Read upstream response status line
        resp_line = await asyncio.wait_for(
            up_reader.readuntil(b'\r\n'), timeout=20
        )
        if b' 200' not in resp_line:
            print(f"[chain] upstream refused: {resp_line!r}")
            client_writer.write(b'HTTP/1.1 502 Bad Gateway\r\n\r\n')
            await client_writer.drain()
            return
        # Drain upstream response headers
        while True:
            line = await asyncio.wait_for(
                up_reader.readuntil(b'\r\n'), timeout=20
            )
            if line == b'\r\n':
                break

        # Tell client we're connected
        client_writer.write(b'HTTP/1.1 200 Connection established\r\n\r\n')
        await client_writer.drain()

        # Bidirectional copy
        async def pipe(r: asyncio.StreamReader, w: asyncio.StreamWriter):
            try:
                while True:
                    chunk = await r.read(65536)
                    if not chunk:
                        break
                    w.write(chunk)
                    await w.drain()
            except (asyncio.CancelledError, Exception):
                pass

        await asyncio.gather(
            pipe(client_reader, up_writer),
            pipe(up_reader, client_writer),
            return_exceptions=True,
        )
    except Exception as e:
        print(f"[chain] handle error: {type(e).__name__}: {e}")
    finally:
        for w in (client_writer, up_writer):
            try:
                if w:
                    w.close()
            except Exception:
                pass


async def serve_one(local_port: int, upstream_url: str):
    p = urlparse(upstream_url)
    user = unquote(p.username or "")
    password = unquote(p.password or "")
    auth_b64 = base64.b64encode(f"{user}:{password}".encode()).decode()
    server = await asyncio.start_server(
        lambda r, w: handle_client(r, w, p.hostname, p.port, auth_b64),
        host="127.0.0.1",
        port=local_port,
    )
    short = f"{p.hostname}:{p.port}"
    print(f"[chain] 127.0.0.1:{local_port}  ->  {short}")
    async with server:
        await server.serve_forever()


def _write_local_proxies_file(count: int):
    """Auto-generate the crawler-facing proxies.txt with local 127.0.0.1 URLs."""
    lines = ["# Auto-generated by tools/proxy_chain.py — do NOT edit by hand"]
    for i in range(count):
        lines.append(f"http://127.0.0.1:{LOCAL_BASE_PORT + i}")
    config.PROXY_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[chain] wrote {config.PROXY_FILE} ({count} entries)")


async def main():
    upstreams = config.load_upstream_proxies()
    if not upstreams:
        print(f"[chain] no upstream proxies in {config.UPSTREAM_PROXY_FILE} — nothing to do.")
        return
    print(f"[chain] starting {len(upstreams)} local listeners…")
    _write_local_proxies_file(len(upstreams))
    tasks = []
    for i, up in enumerate(upstreams):
        tasks.append(serve_one(LOCAL_BASE_PORT + i, up))
    print(f"[chain] ready. Crawler will use ports {LOCAL_BASE_PORT}–"
          f"{LOCAL_BASE_PORT + len(upstreams) - 1}.")
    print(f"[chain] press Ctrl+C to stop.")
    await asyncio.gather(*tasks)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("[chain] stopped.")
